### ISSUE TITLE
Needless SaveDatabase calls cause performance issues

### ISSUE THREAD

**Issue by holly-hacker** [pmikstacki/SliccDB#10]
Several design decisions of SliccDB can cause performance issues, but the biggest contributor is the calls to `SaveDatabase` every time the graph is updated.

As an example, I'm inserting 10000 nodes into the database:
```cs
var db = new DatabaseConnection("test.db");
db.ClearDatabase();
var sw = Stopwatch.StartNew();
for (int i = 0; i < 10_000; i++)
{
	db.CreateNode(
		properties: new Dictionary<string, string> { { "id", i.ToString() } },
		labels: new HashSet<string> { "item" }
	);
}

var elapsed = sw.Elapsed;
Console.WriteLine(elapsed);
```
This took 20 seconds. Additionally, Rider reported 2.5GB of memory allocations. If I comment out the `SaveDatabase` call in CreateNode, it takes 12ms.

Please add an option to opt out of automatic database saving.

**Comment by pmikstacki** [comment]
## Disclaimer
Since I am now working on my thesis I don't have time neccessary to work on SliccDB. I will look into it in my free time, but unfortunately I don't have one recently...

**Comment by pmikstacki** [comment]
I've added database saving as optional feature.
