### ISSUE TITLE
SliccDB.Explorer fails to build on master branch

### ISSUE THREAD

**Issue by holly-hacker** [pmikstacki/SliccDB#12]
When checking out the master branch of SliccDB and trying to build the SliccDB.Explorer project, it fails when compiling the WPF xaml files.

The relevant errors in the build log are:
```
D:\Projects\DotNet\eetool\SliccDB\SliccDB.Explorer\Utility\DebugParseTreeVisual.xaml(11,10): error MC3074: The tag 'AutomaticGraphLayoutControl' does not exist in XML namespace 'http://mlsagl'. Line 11 Position 10. [D:\Projects\DotNet\eetool\SliccDB\SliccDB.Explorer\SliccDB.Explorer.csproj]
D:\Projects\DotNet\eetool\SliccDB\SliccDB.Explorer\Views\MainWindowView.xaml(67,22): error MC3074: The tag 'AutomaticGraphLayoutControl' does not exist in XML namespace 'http://mlsagl'. Line 67 Position 22. [D:\Projects\DotNet\eetool\SliccDB\SliccDB.Explorer\SliccDB.Explorer.csproj]
D:\Projects\DotNet\eetool\SliccDB\SliccDB.Explorer\Views\QueryResultsView.xaml(18,22): error MC3074: The tag 'AutomaticGraphLayoutControl' does not exist in XML namespace 'http://mlsagl'. Line 18 Position 22. [D:\Projects\DotNet\eetool\SliccDB\SliccDB.Explorer\SliccDB.Explorer.csproj]
```

Full build log:
<details>
<pre>
D:\Projects\DotNet\eetool\SliccDB\SliccDB.Explorer>dotnet build SliccDB.Explorer.csproj
Microsoft (R) Build Engine version 17.0.0+c9eb9dd64 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
D:\Projects\DotNet\eetool\SliccDB\SliccDB\SliccDB.csproj : warning NU1701: Package 'Caliburn.Micro 3.2.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project. [D:\Projects\DotNet\eetool\SliccDB\SliccDB.Explorer\SliccDB.Explorer.csproj]
D:\Projects\DotNet\eetool\SliccDB\SliccDB.Cypher\SliccDB.Cypher.csproj : warning NU1701: Package 'Caliburn.Micro 3.2.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project. [D:\Projects\DotNet\eetool\SliccDB\SliccDB.Explorer\SliccDB.Explorer.csproj]
D:\Projects\DotNet\eetool\SliccDB\SliccDB.Explorer\SliccDB.Explorer.csproj : warning NU1608: Detected package version outside of dependency constraint: Caliburn.Micro.Start 3.2.0 requires Caliburn.Micro (= 3.2.0) but version Caliburn.Micro 4.0.173 was resolved.
D:\Projects\DotNet\eetool\SliccDB\SliccDB\SliccDB.csproj : warning NU1701: Package 'Caliburn.Micro.Core 3.2.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project. [D:\Projects\DotNet\eetool\SliccDB\SliccDB.Explorer\SliccDB.Explorer.csproj]
D:\Projects\DotNet\eetool\SliccDB\SliccDB.Cypher\SliccDB.Cypher.csproj : warning NU1701: Package 'Caliburn.Micro.Core 3.2.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project. [D:\Projects\DotNet\eetool\SliccDB\SliccDB.Explorer\SliccDB.Explorer.csproj]
  All projects are up-to-date for restore.
D:\Projects\DotNet\eetool\SliccDB\SliccDB.Explorer\SliccDB.Explorer.csproj : warning NU1608: Detected package version outside of dependency constraint: Caliburn.Micro.Start 3.2.0 requires Caliburn.Micro (= 3.2.0) but version Caliburn.Micro 4.0.173 was resolved.
D:\Projects\DotNet\eetool\SliccDB\SliccDB.Cypher\SliccDB.Cypher.csproj : warning NU1701: Package 'Caliburn.Micro 3.2.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.
D:\Projects\DotNet\eetool\SliccDB\SliccDB.Cypher\SliccDB.Cypher.csproj : warning NU1701: Package 'Caliburn.Micro.Core 3.2.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.
D:\Projects\DotNet\eetool\SliccDB\SliccDB\SliccDB.csproj : warning NU1701: Package 'Caliburn.Micro 3.2.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.
D:\Projects\DotNet\eetool\SliccDB\SliccDB\SliccDB.csproj : warning NU1701: Package 'Caliburn.Micro.Core 3.2.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.
  SliccDB -> D:\Projects\DotNet\eetool\SliccDB\SliccDB\bin\Debug\netstandard2.0\SliccDB.dll
  SliccDB.Cypher -> D:\Projects\DotNet\eetool\SliccDB\SliccDB.Cypher\bin\Debug\netstandard2.0\SliccDB.Cypher.dll
C:\Program Files\dotnet\sdk\6.0.100\Microsoft.Common.CurrentVersion.targets(2304,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "AutomaticGraphLayout". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [D:\Projects\DotNet\eetool\SliccDB\SliccDB.Explorer\SliccDB.Explorer.csproj]
C:\Program Files\dotnet\sdk\6.0.100\Microsoft.Common.CurrentVersion.targets(2304,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "AutomaticGraphLayout.Drawing". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [D:\Projects\DotNet\eetool\SliccDB\SliccDB.Explorer\SliccDB.Explorer.csproj]
C:\Program Files\dotnet\sdk\6.0.100\Microsoft.Common.CurrentVersion.targets(2304,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Microsoft.Msagl.WpfGraphControl". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [D:\Projects\DotNet\eetool\SliccDB\SliccDB.Explorer\SliccDB.Explorer.csproj]
D:\Projects\DotNet\eetool\SliccDB\SliccDB.Explorer\Utility\DebugParseTreeVisual.xaml(11,10): error MC3074: The tag 'AutomaticGraphLayoutControl' does not exist in XML namespace 'http://mlsagl'. Line 11 Position 10. [D:\Projects\DotNet\eetool\SliccDB\SliccDB.Explorer\SliccDB.Explorer.csproj]
D:\Projects\DotNet\eetool\SliccDB\SliccDB.Explorer\Views\MainWindowView.xaml(67,22): error MC3074: The tag 'AutomaticGraphLayoutControl' does not exist in XML namespace 'http://mlsagl'. Line 67 Position 22. [D:\Projects\DotNet\eetool\SliccDB\SliccDB.Explorer\SliccDB.Explorer.csproj]
D:\Projects\DotNet\eetool\SliccDB\SliccDB.Explorer\Views\QueryResultsView.xaml(18,22): error MC3074: The tag 'AutomaticGraphLayoutControl' does not exist in XML namespace 'http://mlsagl'. Line 18 Position 22. [D:\Projects\DotNet\eetool\SliccDB\SliccDB.Explorer\SliccDB.Explorer.csproj]

Build FAILED.

D:\Projects\DotNet\eetool\SliccDB\SliccDB\SliccDB.csproj : warning NU1701: Package 'Caliburn.Micro 3.2.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project. [D:\Projects\DotNet\eetool\SliccDB\SliccDB.Explorer\SliccDB.Explorer.csproj]
D:\Projects\DotNet\eetool\SliccDB\SliccDB.Cypher\SliccDB.Cypher.csproj : warning NU1701: Package 'Caliburn.Micro 3.2.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project. [D:\Projects\DotNet\eetool\SliccDB\SliccDB.Explorer\SliccDB.Explorer.csproj]
D:\Projects\DotNet\eetool\SliccDB\SliccDB.Explorer\SliccDB.Explorer.csproj : warning NU1608: Detected package version outside of dependency constraint: Caliburn.Micro.Start 3.2.0 requires Caliburn.Micro (= 3.2.0) but version Caliburn.Micro 4.0.173 was resolved.
D:\Projects\DotNet\eetool\SliccDB\SliccDB\SliccDB.csproj : warning NU1701: Package 'Caliburn.Micro.Core 3.2.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project. [D:\Projects\DotNet\eetool\SliccDB\SliccDB.Explorer\SliccDB.Explorer.csproj]
D:\Projects\DotNet\eetool\SliccDB\SliccDB.Cypher\SliccDB.Cypher.csproj : warning NU1701: Package 'Caliburn.Micro.Core 3.2.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project. [D:\Projects\DotNet\eetool\SliccDB\SliccDB.Explorer\SliccDB.Explorer.csproj]
D:\Projects\DotNet\eetool\SliccDB\SliccDB.Explorer\SliccDB.Explorer.csproj : warning NU1608: Detected package version outside of dependency constraint: Caliburn.Micro.Start 3.2.0 requires Caliburn.Micro (= 3.2.0) but version Caliburn.Micro 4.0.173 was resolved.
D:\Projects\DotNet\eetool\SliccDB\SliccDB.Cypher\SliccDB.Cypher.csproj : warning NU1701: Package 'Caliburn.Micro 3.2.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.
D:\Projects\DotNet\eetool\SliccDB\SliccDB.Cypher\SliccDB.Cypher.csproj : warning NU1701: Package 'Caliburn.Micro.Core 3.2.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.
D:\Projects\DotNet\eetool\SliccDB\SliccDB\SliccDB.csproj : warning NU1701: Package 'Caliburn.Micro 3.2.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.
D:\Projects\DotNet\eetool\SliccDB\SliccDB\SliccDB.csproj : warning NU1701: Package 'Caliburn.Micro.Core 3.2.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.
C:\Program Files\dotnet\sdk\6.0.100\Microsoft.Common.CurrentVersion.targets(2304,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "AutomaticGraphLayout". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [D:\Projects\DotNet\eetool\SliccDB\SliccDB.Explorer\SliccDB.Explorer.csproj]
C:\Program Files\dotnet\sdk\6.0.100\Microsoft.Common.CurrentVersion.targets(2304,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "AutomaticGraphLayout.Drawing". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [D:\Projects\DotNet\eetool\SliccDB\SliccDB.Explorer\SliccDB.Explorer.csproj]
C:\Program Files\dotnet\sdk\6.0.100\Microsoft.Common.CurrentVersion.targets(2304,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Microsoft.Msagl.WpfGraphControl". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [D:\Projects\DotNet\eetool\SliccDB\SliccDB.Explorer\SliccDB.Explorer.csproj]
D:\Projects\DotNet\eetool\SliccDB\SliccDB.Explorer\Utility\DebugParseTreeVisual.xaml(11,10): error MC3074: The tag 'AutomaticGraphLayoutControl' does not exist in XML namespace 'http://mlsagl'. Line 11 Position 10. [D:\Projects\DotNet\eetool\SliccDB\SliccDB.Explorer\SliccDB.Explorer.csproj]
D:\Projects\DotNet\eetool\SliccDB\SliccDB.Explorer\Views\MainWindowView.xaml(67,22): error MC3074: The tag 'AutomaticGraphLayoutControl' does not exist in XML namespace 'http://mlsagl'. Line 67 Position 22. [D:\Projects\DotNet\eetool\SliccDB\SliccDB.Explorer\SliccDB.Explorer.csproj]
D:\Projects\DotNet\eetool\SliccDB\SliccDB.Explorer\Views\QueryResultsView.xaml(18,22): error MC3074: The tag 'AutomaticGraphLayoutControl' does not exist in XML namespace 'http://mlsagl'. Line 18 Position 22. [D:\Projects\DotNet\eetool\SliccDB\SliccDB.Explorer\SliccDB.Explorer.csproj]
    13 Warning(s)
    3 Error(s)

Time Elapsed 00:00:01.01

D:\Projects\DotNet\eetool\SliccDB\SliccDB.Explorer>
</pre>
</details>

I am using the latest commit on the master branch, which currently is 9b6972e682b033f6f4daa901106863df7221809f.

**Comment by HoLLy-HaCKeR** [comment]
This is the cause of #5

**Comment by pmikstacki** [comment]
## Disclaimer
Since I am now working on my thesis I don't have time neccessary to work on SliccDB. I will look into it in my free time, but unfortunately I don't have one recently...

I think that's because I have modified automatic graph layout and it somehow doesn't load it as dependencies. I will look into integrating the modified part into the solution.

**Comment by pmikstacki** [comment]
I fixed the issue. It should now build. Please verify on your end to be sure!

**Comment by pmikstacki** [comment]
I've decided to move SliccDB.Explorer to another repo. I will try to make this my thesis topic. We'll see how it goes...

**Comment by holly-hacker** [comment]
I'm currently not using SliccDB for any projects, so you're free to close this issue if you want :)

Good luck on your thesis!

**Comment by pmikstacki** [comment]
Thanks! I successfully changed my thesis topic to be an app based on SliccDB, so I am already working on Schema functionality (for ORM to work) 
I am closing this thread. Have a great day!
