### ISSUE TITLE
Asking for help on the storage engine of Neo4j

### ISSUE THREAD

**Issue by GaoDong666** [pmikstacki/SliccDB#7]
Hello!
It seems that you drew experience from Neo4j when designing and implementing SliccDB and achieved great success！
For experimental purposes, I need to modify Neo4j's storage engine and reimplement the underlying data structures like nodes, relationships and graphs in another way.  Could you please tell me which parts of the Neo4j's source code should I modify?
Thank You!

**Comment by pmikstacki** [comment]
Hello, sorry for the late reply. 
I've never read through Neo4J code. I drew inspiration from how the Cypher langugage works. 
I think that there is a possibility of implementing your own structures in older version (pre-bolt era when neo4j was only a Java library). I suggest looking there to find your solution. 
Kind Regards,
Piotr Mikstacki
