### ISSUE TITLE
Create NuGet package

### ISSUE THREAD

**Issue by holly-hacker** [pmikstacki/SliccDB#8]
I wanted to use SliccDB in a project but it does not seem to have a NuGet package, which makes it hard to add. Could you consider publishing a NuGet package?

**Comment by pmikstacki** [comment]
Hello, sorry for the late reply. Since I am now working on my thesis I don't have time neccessary to work on SliccDB. I will look into it in my free time, but unfortunately I don't have one recently...
Kind Regards,
Piotr Mikstacki

**Comment by pmikstacki** [comment]
Nuget package was created and pushed to [nuget.org](https://www.tecmint.com/inxi-command-to-find-linux-system-information/)
